# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_or_kitsu_link', models.URLField()),
                ('mode', models.CharField(choices=[('&status=completed', 'Completed'), ('&status=current', 'Currently watching'), ('&status=planned', 'Plan to watch'), ('&status=completed', 'On hold'), ('&status=dropped', 'droped')], default='&status=completed', max_length=8)),
                ('order', models.CharField(choices=[('?sort=-rating', 'Highest first'), ('?sort=rating', 'Lowest first'), ('?sort=watched', 'Oldest')], default='?sort=-rating', max_length=25)),
                ('tv_size', models.BooleanField()),
                ('youtube_link', models.TextField(blank=True)),
            ],
        ),
    ]
